<?php

namespace Drupal\coherence_core\Plugin\Condition;

use Drupal\Core\Condition\ConditionPluginBase;
use Drupal\Core\Entity\EntityFieldManagerInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a 'Node field is not empty' condition.
 *
 * @Condition(
 *   id = "node_field_is_not_empty",
 *   label = @Translation("Node field is not empty")
 * )
 */
class NodeFieldIsNotEmpty extends ConditionPluginBase implements ContainerFactoryPluginInterface
{

  /**
   * @var RouteMatchInterface
   */
  protected $routeMatch;

  /**
   * @var EntityFieldManagerInterface
   */
  protected $fieldManager;

  /**
   * {@inheritdoc}
   */
  public function __construct(array $configuration, $plugin_id, $plugin_definition, RouteMatchInterface $route_match, EntityFieldManagerInterface $field_manager)
  {
    parent::__construct($configuration, $plugin_id, $plugin_definition);

    $this->routeMatch = $route_match;
    $this->fieldManager = $field_manager;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition)
  {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('current_route_match'),
      $container->get('entity_field.manager')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state)
  {
    $field_map = $this->fieldManager->getFieldMap();
    if (isset($field_map['node']) && count($field_map['node'])) {
      $keys = array_keys($field_map['node']);

      $form['field'] = [
        '#title' => $this->t('Field'),
        '#type' => 'select',
        '#options' => ['' => '-- None --'] + array_combine($keys, $keys),
        '#default_value' => $this->configuration['field'] ?? '',
      ];
    } else {
      $form['error'] = [
        '#markup' => '<p>No relevant fields were found.</p>',
      ];
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state)
  {
    $this->configuration['field'] = $form_state->getValue('field');

    parent::submitConfigurationForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function evaluate()
  {
    // The condition should pass unless we're explicitly evaluating.
    if (!mb_strlen($this->configuration['field'])) {
      return TRUE;
    }

    // This should work on node view and node preview.
    $route_name = $this->routeMatch->getRouteName();

    $node = NULL;
    if ($route_name == 'entity.node.canonical') {
      $node = $this->routeMatch->getParameter('node');
    }
    else if ($route_name == 'entity.node.preview') {
      $node = $this->routeMatch->getParameter('node_preview');
    }

    if ($node instanceof NodeInterface && $node->hasField($this->configuration['field'])) {
      return !$node->get($this->configuration['field'])->isEmpty();
    }

    return FALSE;
  }

  /**
   * {@inheritdoc}
   */
  public function summary()
  {
    return $this->t('Condition to determine whether the currently viewed node has an image field with a value.');
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheContexts()
  {
    return parent::getCacheContexts(); // TODO: Change the autogenerated stub
  }

}